/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moduloAtualizaProjeto;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import moduloAtualizaProjeto.Bundle;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//teste_modulo//tela//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "telaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "teste_modulo.telaTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_telaAction",
        preferredID = "telaTopComponent"
)
@Messages({
    "CTL_telaAction=tela",
    "CTL_telaTopComponent=tela Window",
    "HINT_telaTopComponent=This is a tela window"
})
public final class telaTopComponent extends TopComponent {

    public telaTopComponent() {
        initComponents();
        setName(Bundle.CTL_telaTopComponent());
        setToolTipText(Bundle.HINT_telaTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        painelAlterVersao = new javax.swing.JPanel();
        jComboBoxVersao = new javax.swing.JComboBox<>();
        jButtonAlterVersao = new javax.swing.JButton();
        jComboBoxAlterVersao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelTag = new javax.swing.JPanel();
        jTextFieldTag = new javax.swing.JTextField();
        jButtonAlterTag = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxAlterTag = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLog = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanelCaminhoRepoLocal = new javax.swing.JPanel();
        jTextFieldCaminhoRepoLocaGweb = new javax.swing.JTextField();
        jTextFieldCaminhoRepoLocaGwLib = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoLocaWebtrans = new javax.swing.JTextField();
        jPanelCaminhoRepoRemoto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoRemotoWebtrans = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoRemotoGweb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CaminhoRepoRemotoGwlib = new javax.swing.JTextField();

        painelAlterVersao.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.painelAlterVersao.border.title"))); // NOI18N

        jComboBoxVersao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "master", "atual", "custom" }));

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAlterVersao, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jButtonAlterVersao.text")); // NOI18N
        jButtonAlterVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterVersaoActionPerformed(evt);
            }
        });

        jComboBoxAlterVersao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Webtrans", "Gweb" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout painelAlterVersaoLayout = new javax.swing.GroupLayout(painelAlterVersao);
        painelAlterVersao.setLayout(painelAlterVersaoLayout);
        painelAlterVersaoLayout.setHorizontalGroup(
            painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterVersaoLayout.createSequentialGroup()
                .addComponent(jComboBoxAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAlterVersaoLayout.setVerticalGroup(
            painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAlterVersao)
                .addComponent(jComboBoxAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
        );

        jPanelTag.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelTag.border.title"))); // NOI18N

        jTextFieldTag.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldTag.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAlterTag, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jButtonAlterTag.text")); // NOI18N
        jButtonAlterTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterTagActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel4.text")); // NOI18N

        jComboBoxAlterTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Webtrans", "Gweb" }));

        javax.swing.GroupLayout jPanelTagLayout = new javax.swing.GroupLayout(jPanelTag);
        jPanelTag.setLayout(jPanelTagLayout);
        jPanelTagLayout.setHorizontalGroup(
            jPanelTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTagLayout.createSequentialGroup()
                .addComponent(jComboBoxAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTag, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelTagLayout.setVerticalGroup(
            jPanelTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterTag)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jTextPaneLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(painelAlterVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanelCaminhoRepoLocal.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelCaminhoRepoLocal.border.title"))); // NOI18N

        jTextFieldCaminhoRepoLocaGweb.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaGweb.text")); // NOI18N

        jTextFieldCaminhoRepoLocaGwLib.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaGwLib.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel3.text")); // NOI18N

        jTextFieldCaminhoRepoLocaWebtrans.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaWebtrans.text")); // NOI18N
        jTextFieldCaminhoRepoLocaWebtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoRepoLocaWebtransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCaminhoRepoLocalLayout = new javax.swing.GroupLayout(jPanelCaminhoRepoLocal);
        jPanelCaminhoRepoLocal.setLayout(jPanelCaminhoRepoLocalLayout);
        jPanelCaminhoRepoLocalLayout.setHorizontalGroup(
            jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoLocalLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCaminhoRepoLocaGweb)
                    .addComponent(jTextFieldCaminhoRepoLocaGwLib)
                    .addComponent(jTextFieldCaminhoRepoLocaWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCaminhoRepoLocalLayout.setVerticalGroup(
            jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoLocalLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCaminhoRepoLocaWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCaminhoRepoLocaGweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCaminhoRepoLocaGwLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCaminhoRepoRemoto.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelCaminhoRepoRemoto.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel6.text")); // NOI18N

        jTextFieldCaminhoRepoRemotoWebtrans.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoRemotoWebtrans.text")); // NOI18N
        jTextFieldCaminhoRepoRemotoWebtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoRepoRemotoWebtransActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel7.text")); // NOI18N

        jTextFieldCaminhoRepoRemotoGweb.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoRemotoGweb.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel8.text")); // NOI18N

        CaminhoRepoRemotoGwlib.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.CaminhoRepoRemotoGwlib.text")); // NOI18N

        javax.swing.GroupLayout jPanelCaminhoRepoRemotoLayout = new javax.swing.GroupLayout(jPanelCaminhoRepoRemoto);
        jPanelCaminhoRepoRemoto.setLayout(jPanelCaminhoRepoRemotoLayout);
        jPanelCaminhoRepoRemotoLayout.setHorizontalGroup(
            jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoRemotoLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCaminhoRepoRemotoGweb)
                    .addComponent(CaminhoRepoRemotoGwlib)
                    .addComponent(jTextFieldCaminhoRepoRemotoWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCaminhoRepoRemotoLayout.setVerticalGroup(
            jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoRemotoLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCaminhoRepoRemotoWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCaminhoRepoRemotoGweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CaminhoRepoRemotoGwlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCaminhoRepoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCaminhoRepoRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCaminhoRepoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCaminhoRepoRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCaminhoRepoLocaWebtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoRepoLocaWebtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoRepoLocaWebtransActionPerformed

    private void jTextFieldCaminhoRepoRemotoWebtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoRepoRemotoWebtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoRepoRemotoWebtransActionPerformed

    private void jButtonAlterTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterTagActionPerformed

    private void jButtonAlterVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterVersaoActionPerformed
        AlterarVersao();
    }//GEN-LAST:event_jButtonAlterVersaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaminhoRepoRemotoGwlib;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAlterTag;
    private javax.swing.JButton jButtonAlterVersao;
    private javax.swing.JComboBox<String> jComboBoxAlterTag;
    private javax.swing.JComboBox<String> jComboBoxAlterVersao;
    private javax.swing.JComboBox<String> jComboBoxVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCaminhoRepoLocal;
    private javax.swing.JPanel jPanelCaminhoRepoRemoto;
    private javax.swing.JPanel jPanelTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaGwLib;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaGweb;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaWebtrans;
    private javax.swing.JTextField jTextFieldCaminhoRepoRemotoGweb;
    private javax.swing.JTextField jTextFieldCaminhoRepoRemotoWebtrans;
    private javax.swing.JTextField jTextFieldTag;
    private javax.swing.JTextPane jTextPaneLog;
    private javax.swing.JPanel painelAlterVersao;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void AlterarVersao() {
        String caminhoLocal = "", caminhoRemoto = "", branch = "";

        //branch
        switch (jComboBoxVersao.getSelectedIndex()) {
            case 0:
                branch = "master";
                break;
            case 1:
                branch = "atual";
                break;
            case 2:
                branch = "custom";
                break;
        }

        switch (jComboBoxAlterVersao.getSelectedIndex()) {
            case 0://webtrans
                caminhoLocal = jTextFieldCaminhoRepoLocaWebtrans.getText();
                caminhoRemoto = jTextFieldCaminhoRepoRemotoWebtrans.getText();
                break;
            case 1://gweb
                caminhoLocal = jTextFieldCaminhoRepoLocaGweb.getText();
                caminhoRemoto = jTextFieldCaminhoRepoRemotoGweb.getText();
                break;
        }

        String comando = comandoAtualizarVersao(caminhoLocal, caminhoRemoto, branch);
                
        jTextPaneLog.setText(comando);
        
        executeCommand(comando);
    }
    
    private void AlterarTag() {
        String caminhoLocal = "", caminhoRemoto = "", tag = "";

        tag = jTextFieldTag.getText();

        switch (jComboBoxAlterTag.getSelectedIndex()) {
            case 0://webtrans
                caminhoLocal = jTextFieldCaminhoRepoLocaWebtrans.getText();
                caminhoRemoto = jTextFieldCaminhoRepoRemotoWebtrans.getText();
                break;
            case 1://gweb
                caminhoLocal = jTextFieldCaminhoRepoLocaGweb.getText();
                caminhoRemoto = jTextFieldCaminhoRepoRemotoGweb.getText();
                break;
        }

        String comando = comandoAlterarTag(caminhoLocal, caminhoRemoto, tag);
                
        jTextPaneLog.setText(comando); 
        
        executeCommand(comando);
    }

    private String comandoAtualizarVersao(String caminhoDir, String caminhoRemoto, String branch) {
        return "cd "
                .concat(caminhoDir)
                .concat(" && pwd && git fetch ")
                .concat(caminhoRemoto)
                .concat(" && git checkout ")
                .concat(branch)
                .concat(" && git reset --hard ")
                .concat(caminhoRemoto)
                .concat("/")
                .concat(branch);
    }
    
    private String comandoAlterarTag(String caminhoDir, String caminhoRemoto, String tag ) {
        return "cd "
                .concat(caminhoDir)
                .concat(" && pwd && git fetch --tags ")
                .concat(caminhoRemoto)
                .concat(" && git checkout tags/")
                .concat(tag)
                .concat(" -b ")
                .concat(tag);
    }
    
    public void executeCommand(final String command) {

        final ArrayList<String> commands = new ArrayList<String>();
        commands.add("/bin/bash");
        commands.add("-c");
        commands.add(command);

        BufferedReader br = null;

        try {
            final ProcessBuilder p = new ProcessBuilder(commands);
            final Process process = p.start();
            final InputStream is = process.getInputStream();
            final InputStreamReader isr = new InputStreamReader(is);
            br = new BufferedReader(isr);

            String line;
            while((line = br.readLine()) != null) {
                System.out.println("Retorno do comando = [" + line + "]");
            }
        } catch (Exception ioe) {

        } finally {
            secureClose(br);
        }
    }

    private void secureClose(final Closeable resource) {
        try {
            if (resource != null) {
                resource.close();
            }
        } catch (IOException ex) {
            
        }
    }
}

