/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moduloAtualizaProjeto;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import moduloAtualizaProjeto.Bundle;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//teste_modulo//tela//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "telaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "teste_modulo.telaTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_telaAction",
        preferredID = "telaTopComponent"
)
@Messages({
    "CTL_telaAction=tela",
    "CTL_telaTopComponent=Atualizar Projetos GW",
    "HINT_telaTopComponent=This is a tela window"
})
public final class telaTopComponent extends TopComponent {

    public telaTopComponent() {
        initComponents();
        setName(Bundle.CTL_telaTopComponent());
        setToolTipText(Bundle.HINT_telaTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        painelAlterVersao = new javax.swing.JPanel();
        jComboBoxVersao = new javax.swing.JComboBox<>();
        jButtonAlterVersao = new javax.swing.JButton();
        jComboBoxAlterVersao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLogVersao = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelTag1 = new javax.swing.JPanel();
        jTextFieldTag = new javax.swing.JTextField();
        jButtonAlterTag = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxAlterTag = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneLogTag = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanelCaminhoRepoLocal = new javax.swing.JPanel();
        jTextFieldCaminhoRepoLocaGweb = new javax.swing.JTextField();
        jTextFieldCaminhoRepoLocaGwLib = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoLocaWebtrans = new javax.swing.JTextField();
        jPanelCaminhoRepoRemoto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoRemotoWebtrans = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCaminhoRepoRemotoGweb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CaminhoRepoRemotoGwlib = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmailSSH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSenhaSSH = new javax.swing.JTextField();
        jButtonGerarChave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLogSSH = new javax.swing.JTextArea();

        painelAlterVersao.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.painelAlterVersao.border.title"))); // NOI18N

        jComboBoxVersao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "master", "atual", "custom" }));

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAlterVersao, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jButtonAlterVersao.text")); // NOI18N
        jButtonAlterVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterVersaoActionPerformed(evt);
            }
        });

        jComboBoxAlterVersao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Webtrans", "Gweb" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout painelAlterVersaoLayout = new javax.swing.GroupLayout(painelAlterVersao);
        painelAlterVersao.setLayout(painelAlterVersaoLayout);
        painelAlterVersaoLayout.setHorizontalGroup(
            painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterVersaoLayout.createSequentialGroup()
                .addComponent(jComboBoxAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        painelAlterVersaoLayout.setVerticalGroup(
            painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAlterVersao)
                .addComponent(jComboBoxAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
        );

        jScrollPane1.setViewportView(jTextPaneLogVersao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(painelAlterVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAlterVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanelTag1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelTag1.border.title"))); // NOI18N
        jPanelTag1.setMaximumSize(new java.awt.Dimension(492, 53));

        jTextFieldTag.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldTag.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAlterTag, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jButtonAlterTag.text")); // NOI18N
        jButtonAlterTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterTagActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel9.text")); // NOI18N

        jComboBoxAlterTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Webtrans", "Gweb" }));

        javax.swing.GroupLayout jPanelTag1Layout = new javax.swing.GroupLayout(jPanelTag1);
        jPanelTag1.setLayout(jPanelTag1Layout);
        jPanelTag1Layout.setHorizontalGroup(
            jPanelTag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTag1Layout.createSequentialGroup()
                .addComponent(jComboBoxAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTag, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelTag1Layout.setVerticalGroup(
            jPanelTag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAlterTag)
                .addComponent(jLabel9)
                .addComponent(jComboBoxAlterTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jTextPaneLogTag);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTag1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanelCaminhoRepoLocal.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelCaminhoRepoLocal.border.title"))); // NOI18N

        jTextFieldCaminhoRepoLocaGweb.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaGweb.text")); // NOI18N

        jTextFieldCaminhoRepoLocaGwLib.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaGwLib.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel3.text")); // NOI18N

        jTextFieldCaminhoRepoLocaWebtrans.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoLocaWebtrans.text")); // NOI18N
        jTextFieldCaminhoRepoLocaWebtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoRepoLocaWebtransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCaminhoRepoLocalLayout = new javax.swing.GroupLayout(jPanelCaminhoRepoLocal);
        jPanelCaminhoRepoLocal.setLayout(jPanelCaminhoRepoLocalLayout);
        jPanelCaminhoRepoLocalLayout.setHorizontalGroup(
            jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoLocalLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCaminhoRepoLocaGweb)
                    .addComponent(jTextFieldCaminhoRepoLocaGwLib)
                    .addComponent(jTextFieldCaminhoRepoLocaWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCaminhoRepoLocalLayout.setVerticalGroup(
            jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoLocalLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCaminhoRepoLocaWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCaminhoRepoLocaGweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCaminhoRepoLocaGwLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCaminhoRepoRemoto.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanelCaminhoRepoRemoto.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel6.text")); // NOI18N

        jTextFieldCaminhoRepoRemotoWebtrans.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoRemotoWebtrans.text")); // NOI18N
        jTextFieldCaminhoRepoRemotoWebtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoRepoRemotoWebtransActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel7.text")); // NOI18N

        jTextFieldCaminhoRepoRemotoGweb.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldCaminhoRepoRemotoGweb.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel8.text")); // NOI18N

        CaminhoRepoRemotoGwlib.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.CaminhoRepoRemotoGwlib.text")); // NOI18N

        javax.swing.GroupLayout jPanelCaminhoRepoRemotoLayout = new javax.swing.GroupLayout(jPanelCaminhoRepoRemoto);
        jPanelCaminhoRepoRemoto.setLayout(jPanelCaminhoRepoRemotoLayout);
        jPanelCaminhoRepoRemotoLayout.setHorizontalGroup(
            jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoRemotoLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCaminhoRepoRemotoGweb)
                    .addComponent(CaminhoRepoRemotoGwlib)
                    .addComponent(jTextFieldCaminhoRepoRemotoWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCaminhoRepoRemotoLayout.setVerticalGroup(
            jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaminhoRepoRemotoLayout.createSequentialGroup()
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCaminhoRepoRemotoWebtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCaminhoRepoRemotoGweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaminhoRepoRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CaminhoRepoRemotoGwlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCaminhoRepoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCaminhoRepoRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCaminhoRepoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCaminhoRepoRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel5.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel4.text")); // NOI18N

        jTextFieldEmailSSH.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldEmailSSH.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jLabel10.text")); // NOI18N

        jTextFieldSenhaSSH.setText(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jTextFieldSenhaSSH.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonGerarChave, org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jButtonGerarChave.text")); // NOI18N
        jButtonGerarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarChaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEmailSSH, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSenhaSSH, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGerarChave)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmailSSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldSenhaSSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerarChave))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTextAreaLogSSH.setColumns(20);
        jTextAreaLogSSH.setRows(5);
        jScrollPane3.setViewportView(jTextAreaLogSSH);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(telaTopComponent.class, "telaTopComponent.jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCaminhoRepoRemotoWebtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoRepoRemotoWebtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoRepoRemotoWebtransActionPerformed

    private void jTextFieldCaminhoRepoLocaWebtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoRepoLocaWebtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoRepoLocaWebtransActionPerformed

    private void jButtonAlterTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterTagActionPerformed
        AlterarTag();
    }//GEN-LAST:event_jButtonAlterTagActionPerformed

    private void jButtonAlterVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterVersaoActionPerformed
        AlterarVersao();
    }//GEN-LAST:event_jButtonAlterVersaoActionPerformed

    private void jButtonGerarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarChaveActionPerformed
        gerarChaveSSH();
    }//GEN-LAST:event_jButtonGerarChaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaminhoRepoRemotoGwlib;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAlterTag;
    private javax.swing.JButton jButtonAlterVersao;
    private javax.swing.JButton jButtonGerarChave;
    private javax.swing.JComboBox<String> jComboBoxAlterTag;
    private javax.swing.JComboBox<String> jComboBoxAlterVersao;
    private javax.swing.JComboBox<String> jComboBoxVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCaminhoRepoLocal;
    private javax.swing.JPanel jPanelCaminhoRepoRemoto;
    private javax.swing.JPanel jPanelTag1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextAreaLogSSH;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaGwLib;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaGweb;
    private javax.swing.JTextField jTextFieldCaminhoRepoLocaWebtrans;
    private javax.swing.JTextField jTextFieldCaminhoRepoRemotoGweb;
    private javax.swing.JTextField jTextFieldCaminhoRepoRemotoWebtrans;
    private javax.swing.JTextField jTextFieldEmailSSH;
    private javax.swing.JTextField jTextFieldSenhaSSH;
    private javax.swing.JTextField jTextFieldTag;
    private javax.swing.JTextPane jTextPaneLogTag;
    private javax.swing.JTextPane jTextPaneLogVersao;
    private javax.swing.JPanel painelAlterVersao;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void AlterarVersao() {
        try {
            String caminhoLocal = "", caminhoRemoto = "", branch = "", comando = "",
                    caminhoLocalLib = "", caminhoRemotoLib = "";
            //branch
            switch (jComboBoxVersao.getSelectedIndex()) {
                case 0:
                    branch = "master";
                    break;
                case 1:
                    branch = "atual";
                    break;
                case 2:
                    branch = "custom";
                    break;
            }

            switch (jComboBoxAlterVersao.getSelectedIndex()) {
                case 0://webtrans
                    caminhoLocal = jTextFieldCaminhoRepoLocaWebtrans.getText();
                    caminhoRemoto = jTextFieldCaminhoRepoRemotoWebtrans.getText();
                    break;
                case 1://gweb
                    caminhoLocal = jTextFieldCaminhoRepoLocaGweb.getText();
                    caminhoRemoto = jTextFieldCaminhoRepoRemotoGweb.getText();
                    break;
            }
            
            caminhoLocalLib = jTextFieldCaminhoRepoLocaGwLib.getText();
            caminhoRemotoLib = CaminhoRepoRemotoGwlib.getText();
            
            comando = comandoAtualizarVersao(caminhoLocal, caminhoRemoto, branch);
            comando = comando + " && " + comandoAtualizarVersao(caminhoLocalLib, caminhoRemotoLib, branch);
                    
            executeCommand(comando, "versao");
        } catch (Exception e) {
            mensagem(e.getMessage());
        }
    }

    private void AlterarTag() {
        try {
            String caminhoLocal = "", caminhoRemoto = "", tag = "", comando = "",
                    caminhoLocalLib = "", caminhoRemotoLib = "";

            tag = jTextFieldTag.getText();

            switch (jComboBoxAlterTag.getSelectedIndex()) {
                case 0://webtrans
                    caminhoLocal = jTextFieldCaminhoRepoLocaWebtrans.getText();
                    caminhoRemoto = jTextFieldCaminhoRepoRemotoWebtrans.getText();
                    break;
                case 1://gweb
                    caminhoLocal = jTextFieldCaminhoRepoLocaGweb.getText();
                    caminhoRemoto = jTextFieldCaminhoRepoRemotoGweb.getText();
                    break;
            }
            
            caminhoLocalLib = jTextFieldCaminhoRepoLocaGwLib.getText();
            caminhoRemotoLib = CaminhoRepoRemotoGwlib.getText();
            
            comando = comandoAlterarTag(caminhoLocal, caminhoRemoto, tag);
            comando = comando + " && " + comandoAlterarTag(caminhoLocalLib, caminhoRemotoLib, tag);
                    
            executeCommand(comando, "tag");
        } catch (Exception e) {
            mensagem(e.getMessage());
        }
    }
    
    private void gerarChaveSSH() {
        try {
            String comando = "", email = "", senha = "";
            email = jTextFieldEmailSSH.getText();
            senha = jTextFieldSenhaSSH.getText();            
            comando = comandoGerarChaveSSH(senha, email);
            executeCommand(comando, "chave");
        } catch (Exception ex) {
            mensagem(ex.getMessage());
        }
    }

    private String comandoAtualizarVersao(String caminhoDir, String caminhoRemoto, String branch) {
        return "cd "
                .concat(caminhoDir)
                .concat(" && pwd && git fetch ")
                .concat(caminhoRemoto)
                .concat(" && git checkout ")
                .concat(branch)
                .concat(" && git reset --hard ")
                .concat(caminhoRemoto)
                .concat("/")
                .concat(branch);
    }

    private String comandoAlterarTag(String caminhoDir, String caminhoRemoto, String tag ) {
        return "cd "
                .concat(caminhoDir)
                .concat(" && pwd && git fetch --tags ")
                .concat(caminhoRemoto)
                .concat(" && git checkout tags/")
                .concat(tag)
                .concat(" -b ")
                .concat(tag);
    }
    
    private String comandoGerarChaveSSH(String senha, String email) {
        return "ssh-keygen -t rsa -b 4096 -C \"".concat(email).concat("\" -N ")
                .concat(senha)
                .concat(" -f $HOME/.ssh/id_rsa ")
                .concat(" && cd $HOME/.ssh/ ")
                .concat(" && pwd ")
                .concat(" && cat id_rsa.pub");
    }

    public void executeCommand(final String command, String exibirLog) {
        try {
            final ArrayList<String> commands = new ArrayList<String>();
            commands.add("/bin/bash");
            commands.add("-c");
            commands.add(command);

            BufferedReader br = null;

            final ProcessBuilder p = new ProcessBuilder(commands);
            final Process process = p.start();
            final InputStream is = process.getInputStream();
            final InputStreamReader isr = new InputStreamReader(is);
            br = new BufferedReader(isr);

            String line, log = "";
            while ((line = br.readLine()) != null) {
                log = log + line + "\n";
            }
            
            if (exibirLog == "versao") {
                jTextPaneLogVersao.setText(log);
            } else if (exibirLog == "tag") {
                jTextPaneLogTag.setText(log);
            } else if (exibirLog == "chave") {
                jTextAreaLogSSH.setText(log);
            }
            
            secureClose(isr);
        } catch (Exception e) {
            mensagem(e.getMessage());
        }
    }

    private void secureClose(final Closeable resource) {
        try {
            if (resource != null) {
                resource.close();
            }
        } catch (IOException e) {
            mensagem(e.getMessage());
        }
    }

    private void mensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
}
